package com.corochat.app.server.data.implementations;

import com.corochat.app.server.data.AbstractCorochatDatabase;
import com.corochat.app.server.data.UserRepository;
import com.corochat.app.server.data.daos.UserDao;
import com.corochat.app.server.data.names.DataDeletedMessageName;
import com.corochat.app.server.data.names.DataMessageName;
import com.corochat.app.server.data.names.DataUserName;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public final class CorochatDatabase extends AbstractCorochatDatabase {
    private volatile UserDao userDao;
    private static volatile CorochatDatabase INSTANCE = null;

    private final AbstractCorochatDatabase database;
    private final Connection connection;

    private CorochatDatabase() {
        this.database = AbstractCorochatDatabase.getInstance(this);
        this.connection = databaseConnection;
        createAllTables();
        createUniqueIndexEmail();
        createUniqueIndexPseudo();
    }

    public static CorochatDatabase getInstance() {
        if (INSTANCE == null)
            synchronized (UserRepository.class) {
                if (INSTANCE == null)
                    INSTANCE = new CorochatDatabase();
            }
        return INSTANCE;
    }

    @Override
    public UserDao userDao() {
        if (this.userDao != null)
            return this.userDao;
        else synchronized (this) {
            if (this.userDao == null)
                this.userDao = new UserDaoImpl(this);
            return this.userDao;
        }
    }

    public Connection getConnection() {
        return this.connection;
    }

    private void createUserTable() {
        final String createUserTableSQL = "CREATE TABLE " + DataUserName.TABLE_NAME + " (" +
                           DataUserName.COL_ID + " INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY, " + DataUserName.COL_FIRST_NAME + " VARCHAR(255), " +
                           DataUserName.COL_LAST_NAME + " VARCHAR(255), " + DataUserName.COL_PSEUDO + " VARCHAR(255), " +
                           DataUserName.COL_EMAIL + " VARCHAR(255), " + DataUserName.COL_HASHED_PASSWORD + " VARCHAR(255), " +
                           DataUserName.COL_ACTIVE + " INTEGER NOT NULL, " +
                           "CONSTRAINT pk_user PRIMARY KEY(" + DataUserName.COL_ID + "))";

        final String plsql = "DECLARE v_count NUMBER(1);\nBEGIN\n SELECT count(1) " +
                             "INTO v_count " +
                             "FROM dba_tables " +
                             "WHERE table_name in ('" + DataUserName.TABLE_NAME.toUpperCase() + "','" +
                                                        DataMessageName.TABLE_NAME.toUpperCase() + "','" +
                                                        DataDeletedMessageName.TABLE_NAME.toUpperCase()+"');\n" +
                             "IF v_count = 0 THEN\n" +
                             " EXECUTE IMMEDIATE '" + createUserTableSQL + "';\n" +
                             "END IF;\n" +
                             "END;";
        try {
            final Statement statement = this.connection.createStatement();
            statement.executeUpdate(plsql);
            statement.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void createMessageTable() {
        final String createMessageTableSQL = "CREATE TABLE " + DataMessageName.TABLE_NAME + " (" +
                DataMessageName.COL_ID + " INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY, " + DataMessageName.COL_MESSAGE + " VARCHAR(255), " +
                DataMessageName.COL_USER_EMAIL + " VARCHAR(255), " + DataMessageName.COL_DATE + " DATE, " +
                "CONSTRAINT pk_message PRIMARY KEY(" + DataMessageName.COL_ID + "))";

        final String plsql = "DECLARE v_count NUMBER(1);\nBEGIN\n SELECT count(1) " +
                "INTO v_count " +
                "FROM dba_tables " +
                "WHERE table_name = '" + DataMessageName.TABLE_NAME.toUpperCase() + "';\n" +
                "IF v_count = 0 THEN\n" +
                " EXECUTE IMMEDIATE '" + createMessageTableSQL + "';\n" +
                "END IF;\n" +
                "END;";
        try {
            final Statement statement = this.connection.createStatement();
            statement.executeUpdate(plsql);
            statement.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void createDeletedMessageTable(){
        final String createDeletedMessageTableSQL = "CREATE TABLE " + DataDeletedMessageName.TABLE_NAME + " (" +
                DataDeletedMessageName.COL_ID + " INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY, " + DataDeletedMessageName.COL_MESSAGE_ID + " INTEGER, " +
                DataDeletedMessageName.COL_USER_EMAIL + " VARCHAR(255), " +
                "CONSTRAINT pk_deleted_message PRIMARY KEY(" + DataDeletedMessageName.COL_ID + "))";

        final String plsql = "DECLARE v_count NUMBER(1);\nBEGIN\n SELECT count(1) " +
                "INTO v_count " +
                "FROM dba_tables " +
                "WHERE table_name = '" + DataDeletedMessageName.TABLE_NAME.toUpperCase() + "';\n" +
                "IF v_count = 0 THEN\n" +
                " EXECUTE IMMEDIATE '" + createDeletedMessageTableSQL + "';\n" +
                "END IF;\n" +
                "END;";
        try {
            final Statement statement = this.connection.createStatement();
            statement.executeUpdate(plsql);
            statement.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void createAllTables(){
        createUserTable();
        createMessageTable();
        createDeletedMessageTable();
        System.out.println("Tables created successfully");
    }


    private void createUniqueIndexEmail() {
        final String createUniqueIndex = "DECLARE " +
                "already_exists exception; " +
                "columns_indexed exception; " +
                "pragma exception_init(already_exists, -955); " +
                "pragma exception_init(columns_indexed, -1408); " +
                "BEGIN " +
                "EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UNIDX_USER_EMAIL " +
                "ON " + DataUserName.TABLE_NAME +
                " (" + DataUserName.COL_EMAIL + " ASC)'; " +
                "EXCEPTION WHEN already_exists OR columns_indexed " +
                "THEN NULL;" +
                "END;";
        try {
            final Statement statement = this.connection.createStatement();
            statement.executeUpdate(createUniqueIndex);
            System.out.println("Unique index created on " + DataUserName.TABLE_NAME);
            statement.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void createUniqueIndexPseudo() {
        final String createUniqueIndex = "DECLARE " +
                "already_exists exception; " +
                "columns_indexed exception; " +
                "pragma exception_init(already_exists, -955); " +
                "pragma exception_init(columns_indexed, -1408); " +
                "BEGIN " +
                "EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UNIDX_USER_PSEUDO " +
                "ON " + DataUserName.TABLE_NAME +
                " (" + DataUserName.COL_PSEUDO + " ASC)'; " +
                "EXCEPTION WHEN already_exists OR columns_indexed THEN " +
                "NULL;" +
                "END;";
        try {
            final Statement statement = this.connection.createStatement();
            statement.executeUpdate(createUniqueIndex);
            System.out.println("Unique index created on " + DataUserName.TABLE_NAME);
            statement.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
